"""add crawl control plane

Revision ID: 1453286742ae
Revises: ef8c70f6858e
Create Date: 2026-06-25 10:08:06.184960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1453286742ae'
down_revision: Union[str, Sequence[str], None] = 'ef8c70f6858e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('seed_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('request_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_crawl_runs_max_attempts_positive')),
    sa.CheckConstraint('max_depth >= 0', name=op.f('ck_crawl_runs_max_depth_non_negative')),
    sa.CheckConstraint('max_pages > 0', name=op.f('ck_crawl_runs_max_pages_positive')),
    sa.CheckConstraint('request_timeout_seconds > 0', name=op.f('ck_crawl_runs_request_timeout_positive')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_crawl_runs_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs')),
    sa.UniqueConstraint('collection_id', 'idempotency_key', name='collection_idempotency_key_unique')
    )
    op.create_index('ix_crawl_runs_collection_status', 'crawl_runs', ['collection_id', 'status'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crawl_run_id', sa.Uuid(), nullable=False),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('fetched_bytes', sa.Integer(), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_crawl_jobs_attempt_count_non_negative')),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_crawl_jobs_depth_non_negative')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_crawl_jobs_max_attempts_positive')),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], name=op.f('fk_crawl_jobs_crawl_run_id_crawl_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['crawl_jobs.id'], name=op.f('fk_crawl_jobs_parent_job_id_crawl_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_jobs')),
    sa.UniqueConstraint('crawl_run_id', 'normalized_url', name='crawl_run_normalized_url_unique')
    )
    op.create_index('ix_crawl_jobs_claimable', 'crawl_jobs', ['status', 'lease_expires_at', 'created_at'], unique=False)
    op.create_index('ix_crawl_jobs_run_domain', 'crawl_jobs', ['crawl_run_id', 'domain'], unique=False)
    op.create_index('ix_crawl_jobs_run_status', 'crawl_jobs', ['crawl_run_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crawl_jobs_run_status', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_run_domain', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_claimable', table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index('ix_crawl_runs_collection_status', table_name='crawl_runs')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
