"""add crawled documents

Revision ID: 488dd46597ff
Revises: b8f81b0e3767
Create Date: 2026-06-27 20:36:08.092285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488dd46597ff'
down_revision: Union[str, Sequence[str], None] = 'b8f81b0e3767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawled_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('raw_object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], name=op.f('fk_crawled_documents_crawl_job_id_crawl_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawled_documents')),
    sa.UniqueConstraint('crawl_job_id', name='uq_crawled_documents_crawl_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawled_documents')
    # ### end Alembic commands ###
