"""add crawl job worker attribution

Revision ID: b8f81b0e3767
Revises: cfedbd6ed6bb
Create Date: 2026-06-27 19:05:41.327871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f81b0e3767'
down_revision: Union[str, Sequence[str], None] = 'cfedbd6ed6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('last_claimed_by_worker_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_jobs', 'last_claimed_by_worker_id')
    # ### end Alembic commands ###
