"""add worker heartbeats

Revision ID: cfedbd6ed6bb
Revises: 1453286742ae
Create Date: 2026-06-26 13:16:07.360447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfedbd6ed6bb'
down_revision: Union[str, Sequence[str], None] = '1453286742ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'STARTING'"), nullable=False),
    sa.Column('current_job_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_job_id'], ['crawl_jobs.id'], name=op.f('fk_worker_heartbeats_current_job_id_crawl_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_index('ix_worker_heartbeats_status_last_heartbeat_at', 'worker_heartbeats', ['status', 'last_heartbeat_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_heartbeats_status_last_heartbeat_at', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
